PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS auth (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT,
  FOREIGN KEY (username) REFERENCES users(username) ON DELETE SET NULL
);
INSERT INTO auth (username) VALUES (NULL);
